"""update_schema_to_match_models

Revision ID: 7dd27c03edca
Revises: 001_initial_schema
Create Date: 2026-05-18 23:15:19.901940

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite
from alembic import op


# revision identifiers
revision: str = '7dd27c03edca'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_accounts_import_id'), ['import_id'], unique=False)
        batch_op.drop_column('details')
        batch_op.drop_column('type')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('limit')

    with op.batch_alter_table('import_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('total_rows', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('successful_rows', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('failed_rows', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('filename')
        batch_op.drop_column('rows_failed')
        batch_op.drop_column('rows_processed')

    with op.batch_alter_table('stock_holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('purchase_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('import_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('last_price_update', sa.DateTime(), nullable=False))
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
        batch_op.alter_column('purchase_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
        batch_op.alter_column('current_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_stock_holdings_import_id'), ['import_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('import_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('import_id')
        batch_op.drop_column('merchant')

    with op.batch_alter_table('stock_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_holdings_import_id'))
        batch_op.alter_column('current_price',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('purchase_price',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('last_price_update')
        batch_op.drop_column('import_id')
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('company_name')

    with op.batch_alter_table('import_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rows_processed', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('rows_failed', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.drop_column('account_name')
        batch_op.drop_column('account_id')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('failed_rows')
        batch_op.drop_column('successful_rows')
        batch_op.drop_column('total_rows')
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_name')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limit', sa.FLOAT(), nullable=False))
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('amount')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('details', sqlite.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_accounts_import_id'))
        batch_op.alter_column('balance',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
